/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
    "auth": {
        "common": {
            "deleteMultipleError": string;
            "wrongOldPassword": string;
            "invalidEmail": string;
            "invalidUser": string;
            "invalidToken": string;
            "expiredToken": string;
            "wrongVerifyCode": string;
            "wrongPassword": string;
            "invalidPassword": string;
            "featureIsTurnOff": string;
        };
        "customer": {
            "wrongPhoneNumber": string;
            "wrongPassword": string;
            "failPhoneNumber": string;
            "failPassword": string;
            "phoneNumberNotFound": string;
            "customerNotFound": string;
            "blockedAccount": string;
            "unBlockAccount": string;
            "blockedAddPoint": string;
            "unBlockedAddPoint": string;
            "existed": string;
            "wrongOldPassword": string;
        };
        "admin": {
            "invalidEmail": string;
            "wrongPassword": string;
            "failUserName": string;
            "adminNotFound": string;
        };
        "offForgetPassword": string;
        "onThresholdSendOtp": string;
        "blockedLogin": string;
    };
    "common": {
        "word": {
            "name": string;
            "notFound": string;
            "birthDate": string;
            "firebaseIdToken": string;
            "invalid": string;
            "password": string;
            "downloadFileHistory": string;
            "fileRequest": string;
            "systemConfigPoint": string;
            "admin": string;
            "customer": string;
            "user": string;
            "event": string;
            "requestExport": string;
            "file": string;
            "requestImport": string;
            "survey": string;
            "secret": string;
            "systemConfig": string;
            "termsPolicy": string;
            "phoneNumber": string;
            "deviceToken": string;
            "email": string;
            "address": string;
            "imageId": string;
            "newPassword": string;
            "appConfig": string;
            "subject": string;
            "subjectDetail": string;
            "news": string;
            "newsDetail": string;
            "newsToSubject": string;
            "newsToFile": string;
            "appPolicy": string;
            "appPolicyDetail": string;
            "contact": string;
            "referralCode": string;
            "addPointCode": string;
            "customerToken": string;
            "blockedHistory": string;
            "tierConfig": string;
            "serviceInfo": string;
        };
        "exc": {
            "badRequest": string;
            "notFound": string;
            "internalServerError": string;
            "forbidden": string;
            "unauthorized": string;
            "conflict": string;
            "expectationFailed": string;
            "serviceUnavailable": string;
        };
        "validationError": {
            "appCode": string;
            "date": string;
            "required": string;
            "merchantId": string;
        };
        "cannotDeleteItemIsDefaultLang": string;
    };
    "contact": {
        "isExisted": string;
    };
    "news": {
        "isExisted": string;
        "titleIsExisted": string;
        "notFoundNewsDetail": string;
    };
    "subject": {
        "isExisted": string;
        "notFoundSubjectDetail": string;
    };
    "system-config": {
        "common": {
            "systemConfigNotFound": string;
            "invalidTitle": string;
            "invalidStatus": string;
            "invalidLink": string;
            "invalidDesc": string;
            "invalidImage": string;
            "invalidImageId": string;
            "invalidId": string;
            "invalidStartDate": string;
            "invalidEndDate": string;
            "invalidName": string;
            "invalidMaxLength": string;
            "invalidOrdinal": string;
        };
        "popupConfig": {
            "popupConfigNotFound": string;
            "popupConfigItemNotFound": string;
            "popupConfigOrdinalAlready": string;
        };
        "featureConfig": {
            "featureConfigNotFound": string;
            "featureConfigItemNotFound": string;
            "popupConfigItemNotFound": string;
        };
        "ruleConfig": {
            "ruleConfigNotFound": string;
            "ruleConfigItemNotFound": string;
        };
        "eventConfig": {
            "eventConfigNotFound": string;
            "eventConfigItemNotFound": string;
        };
        "homeConfig": {
            "common": {
                "invalidData": string;
                "homeConfigNotFound": string;
            };
        };
        "shareAppConfig": {
            "common": {
                "invalidData": string;
                "shareAppConfigNotFound": string;
            };
        };
        "appPolicy": {
            "reachLimitAppPolicyAmount": string;
        };
    };
    "test": {
        "plain": string;
        "params": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
