name: deploy auto marketing to EKS
on:
  push:
    branches: ['dev', 'stage']

  workflow_dispatch:
    inputs:
      key-deploy-prod:
        type: string
        required: true
        description: This is secret key to deploy to production

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy-dev:
    if: github.ref_name == 'dev'
    name: deploy dev to cluster
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-southeast-1
      ECR_REPOSITORY: auto-marketing-dev
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      EKS_NAME_SPACE: auto-marketing-be
      DEPLOYMENT_NAME: auto-marketing-be-app
      DEPLOYMENT_WORKER_NAME: auto-marketing-be-worker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker cache layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          cache-from: |
            type=local,src=/tmp/.buildx-cache
          cache-to: |
            type=local,dest=/tmp/.buildx-cache-new
          build-args: |
            "SSH_PRIVATE_KEY=${{secrets.SSH_PRIVATE_KEY}}"

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: deploy app to cluster
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_DEV }}
          RELEASE_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha  }}
        with:
          args: set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=${{ env.RELEASE_IMAGE }} -n $EKS_NAME_SPACE

      - name: deploy worker to cluster
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_DEV }}
          RELEASE_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha  }}
        with:
          args: set image deployment/$DEPLOYMENT_WORKER_NAME $DEPLOYMENT_WORKER_NAME=${{ env.RELEASE_IMAGE }} -n $EKS_NAME_SPACE

  deploy-prod:
    if: github.ref_name == 'prod'
    name: deploy prod to cluster
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-southeast-1
      ECR_REPOSITORY: auto-marketing-prod
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      EKS_NAME_SPACE: auto-marketing-be-prod
      DEPLOYMENT_NAME: auto-marketing-be-app
      DEPLOYMENT_WORKER_NAME: auto-marketing-be-worker

    steps:
      - name: Check for Secret key deploy
        id: secret-check
        shell: bash
        run: |
          if [ "${{ secrets.KEY_DEPLOY_PROD }}" == "${{ github.event.inputs.key-deploy-prod }}" ]; then
            echo "valid=true" >> $GITHUB_OUTPUT;
          else
            echo "valid=false" >> $GITHUB_OUTPUT;
          fi

      - if: ${{ steps.secret-check.outputs.valid != 'true' }}
        name: Checking the key deploy prod is valid
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Deploy to env infra fail, we will not deploy service cause the key is fail')

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker cache layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          cache-from: |
            type=local,src=/tmp/.buildx-cache
          cache-to: |
            type=local,dest=/tmp/.buildx-cache-new
          build-args: |
            "SSH_PRIVATE_KEY=${{secrets.SSH_PRIVATE_KEY}}"

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: deploy to cluster
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_PROD }}
          RELEASE_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha  }}
        with:
          args: set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=${{ env.RELEASE_IMAGE }} -n $EKS_NAME_SPACE

      - name: deploy worker to cluster
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_PROD }}
          RELEASE_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha  }}
        with:
          args: set image deployment/$DEPLOYMENT_WORKER_NAME $DEPLOYMENT_WORKER_NAME=${{ env.RELEASE_IMAGE }} -n $EKS_NAME_SPACE
