export enum ConstraintName {
  UQ_POLICIES = 'UQ_POLICIES',
  CHECK_ONE_OF_KEY_OR_URL = 'CHECK_ONE_OF_KEY_OR_URL',
  UQ_EVENT_NAME_PER_MERCHANT = 'UQ_EVENT_NAME_PER_MERCHANT',
  UQ_SYSTEM_CONF_POINT = 'UQ_SYSTEM_CONF_POINT',
  UQ_TIER_CONFIG = 'UQ_TIER_CONFIG',
  UQ_CODE = 'UQ_CODE',
}
