export enum EventEmitterName {
  CACHE_STALED = 'cache.staled',
  NOTI_PUSHED = 'noti.pushed',
  MERCHANT_REGISTERED = 'merchant.registered',
  CUSTOMER_SCANNED = 'customer.scanned',
  ZALO_NOTI_ADDPOINT = 'zalo.noti.addpoint',
  ZALO_NOTI_ORDER = 'zalo.noti.order',
  USER_REFUND_POINT = 'user.refundpoint',
  USER_ORDER_STATUS = 'user.order.status',
  USER_UPDATE_RANK = 'user.update.rank',
  SEND_GRID_EMAIL = 'sendgrid.email',
  MERCHANT_REJECT_REQUEST_REFUND = 'merchant.rejected.refund.request',
  CUSTOMER_DELETED = 'customer.deleted',
  USER_EVOUCHER_CREATED = 'user.evoucher.created',
  USER_EVOUCHER_USED = 'user.evoucher.used',
  ORDER_CREATED = 'order.created',
}
